#!/bin/bash

# IMAGENET

# 111
# ResNet34_another - ResNet18_another 1-01_01
basicBasic='train_ours_111.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar --method 1 --in_method inAuxCF_logitsNToAE_OnlyOne-5 --fusion_method AUXCF --feedback_time 0 --add_param_groups_method all --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --dataset imagenet --num_class 1000 --epochs 90 --weight_decay 1e-4 --num_workers 16 --learning_rate 0.1 --lr_decay_rate 0.1 --in_criterion KL_softmax --blocks_amount_t 4 --blocks_amount_s 4 --scheduler_method MultiStepLR --lr_decay_epochs 30,60,80'
basicBasicOther='train_ours_111.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar --method 1 --in_method inAuxCF_logitsNToAE_OnlyOne-5 --fusion_method AUXCF --feedback_time 0 --add_param_groups_method all --self_method_t bi_directional --self_method_s bi_directional --dataset imagenet --num_class 1000 --epochs 90 --weight_decay 1e-4 --num_workers 16 --learning_rate 0.1 --lr_decay_rate 0.1 --in_criterion KL_softmax --blocks_amount_t 4 --blocks_amount_s 4 --scheduler_method MultiStepLR --lr_decay_epochs 30,60,80'

## inAuxCF_logitsNToAE_OnlyOne-5 + KLsoftmax TpartAll init0.1 decay_rate0.1 method1 AUXCF fwdloss1 四Tblock 四Sblock ilrT5e-3 MultiStep(60,120,160) AELinear Basic
python $basicBasic --batch_size 256 --infwd_loss 1 --learning_rate_t 5e-3 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --fusion_size Small --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/ -t 1-01_01

#--is_resume --checkpoint_s ./save/distill_our/imagenet/our_S-ResNet18_another_T-ResNet34_another_imagenet_MultiStepLR_1-01_01/ResNet18_another_last.pth.tar --checkpoint_t ./save/distill_our/imagenet/our_S-ResNet18_another_T-ResNet34_another_imagenet_MultiStepLR_1-01_01/ResNet34_another_teacher_last.pth.tar
python $basicBasic --batch_size 256 --infwd_loss 1 --learning_rate_t 5e-3 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --fusion_size largeSmall --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/ -t 1-01_02_half

python $basicBasic --batch_size 512 --infwd_loss 1 --learning_rate_t 5e-3 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --fusion_size littleSmall -t 1-01_17_512bs --dataset_dir

python $basicBasicOther --batch_size 128 --infwd_loss 1 --learning_rate_t 5e-3 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic_133 --aux_method_s Basic_133 --fusion_size largeSmall -t 1-01_35_128bs --dataset_dir

python $basicBasicOther --batch_size 256 --infwd_loss 1 --learning_rate_t 5e-3 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic_133 --aux_method_s Basic_133 --fusion_size largeSmall -t 1-01_36_256bs --dataset_dir


#DDP
python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 7 --fusion_size largeSmall -t 1-01_03 --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_04 --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size largeSmall -t 1-01_05 --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_07_512bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size largeSmall -t 1-01_08_512bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 1024 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_09_1024bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 5 --fusion_size littleSmall -t 1-01_10_512bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 5 --fusion_size largeSmall -t 1-01_11_512bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.2 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_12_512bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --seed 2022403 --feedback_time 0 --learning_rate 0.05 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_13_512bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t AELinear --fusion_method_AE_s AELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size Mean -t 1-01_14_512bs --dataset_dir /data1/mazc/gjp/xxm/NKD/data/imagenet/

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --scheduler_method CosineAnnealingLR --CosineSch_Tmax 90 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_15_512bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 5e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_16 --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 5e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_16_512bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 1e-4 --infwd_loss 1 --fusion_size littleSmall -t 1-01_18_512bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 5e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_19_512bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.05 --weight_decay 5e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_20_512bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-4 --infwd_loss 1 --fusion_size littleSmall -t 1-01_21_512bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 128 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_22_128bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Bottle --aux_method_s Bottle --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_23_256bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 10 --fusion_size littleSmall -t 1-01_24_512bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_25_512bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 10 --fusion_size largeSmall -t 1-01_26_512bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.01 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_27_512bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.05 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_28_512bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.01 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_29_256bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.05 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size littleSmall -t 1-01_30_256bs --dataset_droplast --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Bottle --aux_method_s Bottle --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size largeSmall -t 1-01_31_256bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion MSE_normalize --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size largeSmall -t 1-01_32_256bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion MSE_normalize --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 5e-3 --infwd_loss 10 --fusion_size largeSmall -t 1-01_33_256bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic_133 --aux_method_s Basic_133 --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 256 --learning_rate_t 1e-4 --infwd_loss 1 --fusion_size largeSmall -t 1-01_34_256bs --dataset_dir

python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic_133 --aux_method_s Basic_133 --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://127.0.0.1:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size largeSmall -t 1-01_37_512bs --dataset_dir


# Multi Node. multi node 不应该使用 seed
#node 1
python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://10.3.125.97:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 0 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size largeSmall -t 1-01_05 --dataset_dir /home/goujp/cy/Dataset/imagenet/

#node 2
python train_ours_ddp.py --model_s ResNet18_another --model_t ResNet34_another --path_t ./save/base/imagenet/ResNet34_another_imagenet_base/ResNet34_another_teacher_best.pth.tar -p 500 --feedback_time 0 --learning_rate 0.1 --weight_decay 1e-4 --lr_decay_epochs 30,60,80 --lr_decay_rate 0.1 --method 1 --kd_T 4 --fusion_method_AE_t ADPAELinear --fusion_method_AE_s ADPAELinear --aux_method_t Basic --aux_method_s Basic --self_method_t bi_directional --self_method_s bi_directional --in_criterion KL_softmax --dataset imagenet --num_class 1000 --dist-url 'tcp://10.3.125.97:1257' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 1 --batch_size 512 --learning_rate_t 5e-3 --infwd_loss 1 --fusion_size largeSmall -t 1-01_05 --dataset_dir ./data/imagenet

